# Generated by Django 2.2.4 on 2019-11-28 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaovigenciacontrato',
            name='notificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes_vigencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscais', to='contratos.Contrato'),
        ),
        migrations.AddField(
            model_name='contratounidade',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='contratos.Contrato'),
        ),
        migrations.AddField(
            model_name='contratounidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.Unidade'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_coordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_contratada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_da_empresa', to='contratos.Empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_geridos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nucleo_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_nucleo', to='core.Nucleo', verbose_name='núcleo responsável'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_geridos_suplente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_tipo', to='contratos.TipoServico', verbose_name='tipo de serviço'),
        ),
        migrations.AddField(
            model_name='colunascontrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_servidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
