# Generated by Django 2.2.4 on 2019-12-02 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0002_auto_20191128_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratounidade',
            name='dre_lote',
        ),
    ]
