# Generated by Django 2.2.4 on 2019-09-23 17:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('termo_contrato', models.CharField(max_length=20, verbose_name='TC No.')),
                ('processo', models.CharField(max_length=50)),
                ('objeto', models.TextField(blank=True, default='', null=True)),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='data da assinatura')),
                ('data_ordem_inicio', models.DateField(blank=True, null=True, verbose_name='data da ordem de início')),
                ('vigencia_em_meses', models.PositiveSmallIntegerField(default=0)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO',
                                              max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('empresa_contratada',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_da_empresa',
                                   to='contratos.Empresa')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                             related_name='contratos_geridos', to=settings.AUTH_USER_MODEL)),
                ('nucleo_responsavel',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_nucleo',
                                   to='core.Nucleo', verbose_name='núcleo responsável')),
                ('tipo_servico',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_tipo',
                                   to='contratos.TipoServico', verbose_name='tipo de serviço')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='ContratoUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dotacao_orcamentaria', models.CharField(max_length=20)),
                ('lote', models.CharField(blank=True, max_length=20, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades',
                                               to='contratos.Contrato')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos',
                                              to='core.Unidade')),
            ],
            options={
                'verbose_name': 'Unidade de Contrato',
                'verbose_name_plural': 'Unidades de Contratos',
            },
        ),
    ]
