# Generated by Django 2.2.4 on 2019-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0003_contrato_contratounidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='objeto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contratounidade',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
