# Generated by Django 2.2.4 on 2019-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0004_auto_20190923_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratounidade',
            name='dre_lote',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='DRE do lote'),
        ),
    ]
