# Generated by Django 2.2.4 on 2019-12-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0004_fiscaisunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscaisunidade',
            name='contrato_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='fiscais', to='contratos.ContratoUnidade'),
        ),
    ]
