# Generated by Django 2.2.4 on 2019-12-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atestes', '0002_auto_20191129_1718'),
        ('contratos', '0005_auto_20191203_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='modelo_ateste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelo_ateste', to='atestes.ModeloAteste'),
        ),
    ]
