# Generated by Django 2.2.4 on 2019-09-24 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0005_contratounidade_dre_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True,
                                   validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
    ]
