# Generated by Django 2.2.4 on 2020-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contrato_modelo_ateste'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='referencia_encerramento',
            field=models.CharField(choices=[('DATA_ASSINATURA', 'Data de Assinatura'), ('DATA_ORDEM_INICIO', 'Data de Ordem de Inicio')], default='DATA_ORDEM_INICIO', max_length=20),
        ),
    ]
