# Generated by Django 2.2.4 on 2019-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0006_auto_20190924_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervico',
            name='nome',
            field=models.CharField(max_length=160, unique=True, verbose_name='Nome'),
        ),
    ]
