# Generated by Django 2.2.4 on 2020-05-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unidade_sigla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0007_contrato_referencia_encerramento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='contratos.Contrato')),
                ('unidades', models.ManyToManyField(to='core.Unidade')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='FiscalLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_fiscal', models.CharField(choices=[('TITULAR', 'Titular'), ('SUPLENTE', 'Suplente')], default='SUPLENTE', max_length=15)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscais', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='contratos.Lote')),
            ],
            options={
                'verbose_name': 'Fiscal do Lote de Contrato',
                'verbose_name_plural': 'Fiscais dos Lotes de Contratos',
            },
        ),
    ]
