# Generated by Django 2.2.4 on 2019-09-25 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0007_auto_20190924_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='vigencia_em_meses',
            new_name='vigencia_em_dias',
        ),
    ]
