# Generated by Django 2.2.4 on 2019-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0009_contrato_estado_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado_contrato',
            field=models.CharField(
                choices=[('EMERGENCIAL', 'Emergencial'), ('EXCEPCIONAL', 'Excepcional'), ('ULTIMO_ANO', 'Último Ano'),
                         ('VIGENTE', 'Vigente')], default='VIGENTE', max_length=15, verbose_name='estado'),
        ),
    ]
