# Generated by Django 2.2.4 on 2020-05-19 17:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_auto_20200518_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dotacao_orcamentaria',
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado_contrato',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'Vigente'), ('EXCEPCIONAL', 'Excepcional'), ('EMERGENCIAL', 'Emergencial'), ('SUSPENSO_INTERROMPIDO', 'Suspenso / Interrompido')], default='', max_length=30, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='parametronotificacoesvigencia',
            name='estado_contrato',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'Vigente'), ('EXCEPCIONAL', 'Excepcional'), ('EMERGENCIAL', 'Emergencial'), ('SUSPENSO_INTERROMPIDO', 'Suspenso / Interrompido')], default='', max_length=30, verbose_name='Para contratos com estado'),
        ),
        migrations.CreateModel(
            name='DotacaoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dotacao_orcamentaria', models.TextField(default='', verbose_name='Dotação Orçamentária')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotacoes_orcamentarias', to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Dotação Orçamentária',
                'verbose_name_plural': 'Dotações Orçamentárias',
            },
        ),
    ]
