# Generated by Django 2.2.4 on 2020-05-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_fiscallote_lote'),
        ('contratos', '0010_auto_20200519_1426'),
    ]

    operations = [
    ]
