# Generated by Django 2.2.4 on 2020-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_auto_20200519_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='unidade_vigencia',
            field=models.CharField(choices=[('DIAS', 'dias'), ('MESES', 'meses')], default='DIAS', max_length=10),
        ),
    ]
