# Generated by Django 2.2.4 on 2019-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0010_auto_20190927_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
