# Generated by Django 2.2.4 on 2020-05-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_auto_20200519_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacaovalor',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotacoes', to='contratos.Contrato'),
        ),
    ]
