# Generated by Django 2.2.4 on 2020-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_contrato_unidade_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='vigencia_em_dias',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='vigência'),
        ),
    ]
