# Generated by Django 2.2.4 on 2019-10-23 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0012_auto_20191018_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='suplente',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_geridos_suplente', to=settings.AUTH_USER_MODEL),
        ),
    ]
