# Generated by Django 2.2.4 on 2020-05-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_merge_20200519_1852'),
        ('contratos', '0012_auto_20200521_1433'),
    ]

    operations = [
    ]
