# Generated by Django 2.2.4 on 2020-05-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_merge_20200522_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscallote',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscais_lote', to='contratos.Lote'),
        ),
    ]
