# Generated by Django 2.2.4 on 2019-10-23 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_contrato_suplente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('RASCUNHO', 'Rascunho')], default='ATIVO', max_length=15),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_geridos_suplente', to=settings.AUTH_USER_MODEL),
        ),
    ]
