# Generated by Django 2.2.4 on 2019-10-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20191023_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empresa_contratada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_da_empresa', to='contratos.Empresa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado_contrato',
            field=models.CharField(blank=True, choices=[('EMERGENCIAL', 'Emergencial'), ('EXCEPCIONAL', 'Excepcional'), ('ULTIMO_ANO', 'Último Ano'), ('VIGENTE', 'Vigente')], default='', max_length=15, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nucleo_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_nucleo', to='core.Nucleo', verbose_name='núcleo responsável'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='processo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('RASCUNHO', 'Rascunho')], default='RASCUNHO', max_length=15),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_tipo', to='contratos.TipoServico', verbose_name='tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vigencia_em_dias',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
