# Generated by Django 2.2.4 on 2020-05-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_auto_20200526_1124'),
        ('contratos', '0014_auto_20200526_1454'),
    ]

    operations = [
    ]
