# Generated by Django 2.2.4 on 2020-05-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_merge_20200526_1557'),
        ('contratos', '0014_contrato_edital'),
    ]

    operations = [
    ]
