# Generated by Django 2.2.4 on 2019-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_auto_20191024_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='termo_contrato',
            field=models.CharField(max_length=20, unique=True, verbose_name='TC No.'),
        ),
    ]
