# Generated by Django 2.2.4 on 2021-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_merge_20200530_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratounidade',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contratounidade',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
