# Generated by Django 2.2.4 on 2019-10-31 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_auto_20191028_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='documento_fiscal_dre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Anexos Documento Fisca DRE'), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='contrato',
            name='documento_fiscal_unidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Anexos Documento Fisca Unidades'), blank=True, default=list, size=None),
        ),
    ]
