# Generated by Django 2.2.4 on 2019-10-31 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0017_auto_20191031_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='documento_fiscal_dre',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='documento_fiscal_unidades',
        ),
    ]
