# Generated by Django 2.2.4 on 2019-11-03 12:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0017_auto_20191031_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunasContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('colunas_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Lista de campos'), blank=True, default=[{'checked': True, 'field': 'termo_contrato', 'header': 'TC'}, {'checked': True, 'field': 'processo', 'header': 'Processo'}, {'checked': True, 'field': 'tipo_servico.nome', 'header': 'Tipode de Serviço'}, {'checked': True, 'field': 'empresa_contratada.nome', 'header': 'Empresa'}, {'checked': True, 'field': 'estado_contrato', 'header': 'Estado do Contrato'}, {'checked': True, 'field': 'data_encerramento', 'header': 'Data Encerramento'}, {'checked': False, 'field': 'nucleo_responsavel', 'header': 'Núcleo Responsável'}, {'checked': False, 'field': 'objeto', 'header': 'Objeto'}, {'checked': False, 'field': 'data_assinatura', 'header': 'Data Assinatura'}, {'checked': False, 'field': 'data_ordem_inicio', 'header': 'Data Ordem de Inicio'}, {'checked': False, 'field': 'vigencia_em_dias', 'header': 'Vigencia'}, {'checked': False, 'field': 'situacao', 'header': 'Situação'}, {'checked': False, 'field': 'gestor', 'header': 'Gestor'}, {'checked': False, 'field': 'suplente', 'header': 'Suplente'}, {'checked': False, 'field': 'observacoes', 'header': 'Observações'}], size=None)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_servidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colunas do Usuário',
                'verbose_name_plural': 'Colunas do Usuário',
            },
        ),
    ]
