# Generated by Django 2.2.4 on 2022-03-04 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_auto_20210721_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Edital')),
                ('processo', models.CharField(default='', max_length=19)),
                ('tipo_contratacao', models.CharField(choices=[('LICITACAO', 'Licitação'), ('DISPENSA_LICITACAO', 'Dispensa de Licitação'), ('INEXIGIBILIDADE_LICITACAO', 'Inexigibilidade de Licitação"')], default='LICITACAO', max_length=15)),
                ('subtipo', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ATIVO', 'AtivO'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Data de homologação')),
                ('descricao_objeto', models.TextField(blank=True, default='')),
                ('objeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos', to='contratos.TipoServico', verbose_name='Categoria de objeto')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='GrupoObrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_obrigacao', to='contratos.Edital')),
            ],
            options={
                'verbose_name': 'Grupo de Obrigação',
                'verbose_name_plural': 'Grupos de Obrigações',
            },
        ),
        migrations.AlterField(
            model_name='contrato',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contartos_do_edital', to='contratos.Edital'),
        ),
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('item', models.CharField(max_length=15)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_obrigacao', to='contratos.GrupoObrigacao')),
            ],
            options={
                'verbose_name': 'Obrigação',
                'verbose_name_plural': 'Obrigações',
            },
        ),
    ]
