# Generated by Django 2.2.4 on 2019-10-31 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0018_auto_20191031_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='documento_fiscal_dre',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200, verbose_name='Anexos Documento Fisca DRE'), blank=True,
                default=list, size=None),
        ),
        migrations.AddField(
            model_name='contrato',
            name='documento_fiscal_unidades',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200, verbose_name='Anexos Documento Fisca Unidades'), blank=True,
                default=list, size=None),
        ),
    ]
