# Generated by Django 2.2.4 on 2022-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_auto_20220304_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='edital',
            name='tipo_contratacao',
            field=models.CharField(choices=[('LICITACAO', 'Licitação'), ('DISPENSA_LICITACAO', 'Dispensa de Licitação'), ('INEXIGIBILIDADE_LICITACAO', 'Inexigibilidade de Licitação"')], default='LICITACAO', max_length=25),
        ),
    ]
