# Generated by Django 2.2.4 on 2019-11-04 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0018_colunascontrato'),
        ('contratos', '0019_auto_20191031_0914'),
    ]

    operations = [
    ]
