# Generated by Django 2.2.4 on 2019-11-08 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0020_merge_20191106_1452'),
        ('contratos', '0020_merge_20191104_1924'),
    ]

    operations = [
    ]
