# Generated by Django 2.2.4 on 2022-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_auto_20220309_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='tipo_contratacao',
            field=models.CharField(choices=[('LICITACAO', 'Licitação'), ('DISPENSA_LICITACAO', 'Dispensa de Licitação'), ('INEXIGIBILIDADE_LICITACAO', 'Inexigibilidade de Licitação')], default='LICITACAO', max_length=25),
        ),
    ]
