# Generated by Django 2.2.16 on 2022-04-05 17:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_auto_20220310_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número da Ata')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('RASCUNHO', 'Rascunho')], default='RASCUNHO', max_length=10)),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data da assinatura')),
                ('vigencia', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Vigência')),
                ('unidade_vigencia', models.CharField(choices=[('DIAS', 'dias'), ('MESES', 'meses')], default='DIAS', max_length=10)),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('edital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas_do_edital', to='contratos.Edital')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atas', to='contratos.Empresa')),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
            },
        ),
    ]
