# Generated by Django 2.2.16 on 2022-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contato'),
        ('contratos', '0022_ata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contatos',
            field=models.ManyToManyField(blank=True, to='core.Contato'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=160, verbose_name='Endereco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=160, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='situacao',
            field=models.CharField(blank=True, choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=25),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_fornecedor',
            field=models.CharField(blank=True, choices=[('AGRICULTURA_FAMILIAR', 'Agricultura familiar'), ('CONVENCIONAL', 'CONVENCIONAL')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_servico',
            field=models.CharField(choices=[('ARMAZEM/DISTRIBUIDOR', 'Armazém/Distribuidor'), ('FORNECEDOR/DISTRIBUIDOR', 'Fornecedor/Distribuidor'), ('FORNECEDOR', 'Fornecedor')], default='ARMAZEM/DISTRIBUIDOR', max_length=25),
        ),
    ]
