# Generated by Django 2.2.4 on 2019-11-12 19:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0022_auto_20191108_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratounidade',
            name='dotacao_orcamentaria',
        ),
        migrations.AddField(
            model_name='contrato',
            name='dotacao_orcamentaria',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200, verbose_name='Dotação Orçamentária'), blank=True,
                default=list, size=None),
        ),
    ]
