# Generated by Django 2.2.4 on 2019-11-11 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0022_auto_20191108_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametrosNotificacoesVigencia',
            new_name='ParametroNotificacoesVigencia',
        ),
    ]
