# Generated by Django 2.2.4 on 2019-11-12 19:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0023_auto_20191112_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='documento_fiscal_dre',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='documento_fiscal_unidades',
        ),
        migrations.CreateModel(
            name='DocumentosFiscalUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anexo', models.FileField(blank=True, default='', max_length=200, upload_to='', verbose_name='Anexo')),
                ('contrato',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_unidade',
                                   to='contratos.Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentosFiscalDre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anexo', models.FileField(blank=True, default='', max_length=200, upload_to='', verbose_name='Anexo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_dre',
                                               to='contratos.Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
