# Generated by Django 2.2.4 on 2019-11-11 17:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0023_auto_20191111_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoVigenciaContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('validade', models.DateField(verbose_name='validade da notificação')),
                ('contrato',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_vigencia',
                                   to='contratos.Contrato')),
                ('notificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='notificacoes_vigencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação de vigência de contrato',
                'verbose_name_plural': 'Notificações de vigência de contrato',
            },
        ),
    ]
