# Generated by Django 2.2.16 on 2022-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_auto_20220425_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_fornecedor',
            field=models.CharField(blank=True, choices=[('AGRICULTURA_FAMILIAR', 'Agricultura familiar'), ('CONVENCIONAL', 'Convencional')], default='', max_length=25),
        ),
    ]
