# Generated by Django 2.2.16 on 2022-05-05 19:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_auto_20220425_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotacaoOrcamentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('orgao', models.CharField(max_length=2, verbose_name='Órgão')),
                ('unidade', models.CharField(max_length=2, verbose_name='Unidade')),
                ('funcao', models.CharField(max_length=2, verbose_name='Função')),
                ('subfuncao', models.CharField(max_length=3, verbose_name='Subfunção')),
                ('programa', models.CharField(max_length=4, verbose_name='Programa')),
                ('projeto_atividade', models.CharField(max_length=5, verbose_name='Projeto/Atividade')),
                ('conta_despesa', models.CharField(max_length=2, verbose_name='Conta Despesa')),
                ('fonte', models.CharField(max_length=2, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Dotação Orçamentária',
                'verbose_name_plural': 'Dotações Orçamentárias',
            },
        ),
    ]
