# Generated by Django 2.2.4 on 2019-11-12 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0024_notificacaovigenciacontrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaovigenciacontrato',
            name='validade',
        ),
    ]
