# Generated by Django 2.2.4 on 2019-11-12 23:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0024_auto_20191112_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosfiscalunidade',
            name='contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='documentos_fiscais_dre',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200, verbose_name='Anexos Documento Fiscais DRE'), blank=True,
                default=list, size=None),
        ),
        migrations.AddField(
            model_name='contrato',
            name='documentos_fiscais_unidades',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200, verbose_name='Anexos Documento Fiscais Unidades'),
                blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='DocumentosFiscalDre',
        ),
        migrations.DeleteModel(
            name='DocumentosFiscalUnidade',
        ),
    ]
