# Generated by Django 2.2.16 on 2022-05-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_dotacaoorcamentaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotacaovalor',
            options={'verbose_name': 'Dotação Orçamentária (Valor)', 'verbose_name_plural': 'Dotações Orçamentárias (Valor)'},
        ),
    ]
