# Generated by Django 2.2.4 on 2019-11-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0025_auto_20191112_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='documentos_fiscais_dre',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='documentos_fiscais_unidades',
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('anexo', models.FileField(upload_to='uploads/')),
                ('tipo_unidade',
                 models.CharField(choices=[('FISCAL_DRE', 'DRE'), ('FISCAL_UNIDADE', 'UNIDADE')], max_length=20)),
                ('contrato',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscais',
                                   to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
            },
        ),
    ]
