# Generated by Django 2.2.4 on 2019-11-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_auto_20191108_1627'),
        ('contratos', '0025_remove_notificacaovigenciacontrato_validade'),
    ]

    operations = [
    ]
