# Generated by Django 2.2.16 on 2022-04-26 19:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_unidadedemedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=160, unique=True, verbose_name='Nome')),
                ('categoria', models.CharField(blank=True, choices=[('ALIMENTO', 'Alimento'), ('OUTROS', 'Outro(s)')], default='ALIMENTO', max_length=25)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=25)),
                ('grupo_alimentar', models.CharField(blank=True, choices=[('CONGELADOS_E_RESFRIADOS', 'Congelados e resfriados'), ('FLVO', 'FLVO'), ('PAES_E_BOLO', 'Pães e bolos'), ('SECOS', 'Secos')], default='', max_length=25)),
                ('durabilidade', models.CharField(blank=True, choices=[('PERECIVEL', 'Perecível'), ('NAO_PERECIVEL', 'Não perecível')], default='', max_length=25)),
                ('armazenabilidade', models.CharField(choices=[('ARMAZENAVEL', 'Armazenável'), ('NAO_ARMAZENAVEL', 'Não armazenável')], default='ARMAZENAVEL', max_length=25)),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='contratos.UnidadeDeMedida')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
