# Generated by Django 2.2.4 on 2019-11-13 18:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0026_auto_20191113_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
