# Generated by Django 2.2.16 on 2022-05-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_auto_20220506_1141'),
        ('contratos', '0026_produto'),
    ]

    operations = [
    ]
