# Generated by Django 2.2.16 on 2022-05-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_merge_20220511_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='vigencia_em_dias',
            new_name='vigencia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='estado_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contartos_da_ata', to='contratos.Ata'),
        ),
        migrations.AlterField(
            model_name='parametronotificacoesvigencia',
            name='estado_contrato',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Para contratos com estado'),
        ),
    ]
