# Generated by Django 2.2.4 on 2019-11-17 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20191029_1130'),
        ('contratos', '0028_auto_20191113_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='divisao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='core.Divisao', verbose_name='Divisão'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='core.Nucleo', verbose_name='Núcleo'),
        ),
    ]
