# Generated by Django 2.2.16 on 2022-05-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_auto_20220512_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='ata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_da_ata', to='contratos.Ata'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_do_edital', to='contratos.Edital'),
        ),
    ]
