# Generated by Django 2.2.16 on 2022-05-24 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_auto_20220524_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='historico',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
