# Generated by Django 2.2.4 on 2019-11-17 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0030_remove_contrato_nucleo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='divisao',
        ),
    ]
