# Generated by Django 2.2.16 on 2022-05-27 20:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_edital_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacaovalor',
            name='dotacao_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotacoes_por_valor', to='contratos.DotacaoOrcamentaria'),
        ),
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Empenho')),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dotacao_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empenhos', to='contratos.DotacaoValor')),
            ],
            options={
                'verbose_name': 'Empenho',
                'verbose_name_plural': 'Empenhos',
            },
        ),
    ]
