# Generated by Django 2.2.4 on 2019-11-19 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0031_remove_contrato_divisao'),
        ('contratos', '0026_merge_20191118_1728'),
    ]

    operations = [
    ]
