# Generated by Django 2.2.4 on 2019-11-19 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0032_merge_20191119_1201'),
        ('contratos', '0032_merge_20191119_1203'),
    ]

    operations = [
    ]
