# Generated by Django 2.2.16 on 2022-06-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0032_produtosata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='modelo_ateste',
        ),
    ]
