# Generated by Django 2.2.4 on 2019-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0033_obrigacaocontratual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacaocontratual',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes_contratuais',
                                    to='contratos.Contrato'),
        ),
    ]
