# Generated by Django 2.2.4 on 2019-11-22 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0033_merge_20191119_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='contratos_coordenador', to=settings.AUTH_USER_MODEL),
        ),
    ]
