# Generated by Django 2.2.4 on 2019-11-25 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contratos', '0034_auto_20191120_1021'),
        ('contratos', '0034_contrato_coordenador'),
    ]

    operations = [
    ]
