# Generated by Django 2.2.4 on 2019-11-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0034_contrato_coordenador'),
        ('contratos', '0034_auto_20191120_1021'),
    ]

    operations = [
    ]
