# Generated by Django 2.2.16 on 2022-06-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0035_auto_20220627_1158'),
    ]

    operations = [
        mmigrations.AlterField(
            model_name='edital',
            name='objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos', to='contratos.Objeto', verbose_name='Categoria de objeto'),
        ),
        migrations.DeleteModel(
            name='TipoServico',
        ),
    ]
