# Generated by Django 2.2.16 on 2022-06-28 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0036_auto_20220627_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='suplente',
        ),
        migrations.CreateModel(
            name='GestorContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestores', to='contratos.Contrato')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_geridos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestor de Contrato',
                'verbose_name_plural': 'Gestores de Contrato',
            },
        ),
    ]
