# Generated by Django 2.2.16 on 2022-07-13 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0037_auto_20220628_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anexo', models.FileField(upload_to='uploads/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_contrato', to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Anexo de Contrato',
                'verbose_name_plural': 'Anexos de Contratos',
            },
        ),
    ]
