# Generated by Django 2.2.16 on 2022-07-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0038_anexocontrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoFiscal',
        ),
    ]
