# Generated by Django 2.2.16 on 2022-08-05 12:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0039_delete_documentofiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('termo_aditivo', models.CharField(max_length=10, unique=True, verbose_name='TA No.')),
                ('objeto_aditamento', multiselectfield.db.fields.MultiSelectField(choices=[('PRORROGACAO_VIGENCIA_CONTRATUAL', 'Prorrogação da vigência contratual'), ('MODIFICACAO_PROJETO_ESPECIFICACOES', 'Modificação do projeto ou das especificações, para melhor adequação técnica os seus objetivos'), ('MODIFICACAO_VALOR_CONTRATUAL', 'Modificação do valor contratual em decorrência de acréscimo ou diminuição quantitativa de seu objeto'), ('SUBSTITUICAO_GARANTIA_EXECUCAO', 'Substituição da garantia de execução'), ('MODIFICACAO_REGIME_EXECUCAO', 'Modificação do regime de execução da obra ou serviço e do modo de fornecimento'), ('MODIFICACAO_FORMA_PAGAMENTO', 'Modificação da forma de pagamento, por imposição de circunstâncias supervenientes, mantido o valor inicial atualizado')], max_length=182)),
                ('data_inicial', models.DateField(null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(null=True, verbose_name='Data Final')),
                ('valor_mensal_atualizado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('valor_total_atualizado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('valor_aditamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('razoes_aditamento', models.TextField(verbose_name='Razões do aditamento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditamentos', to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Aditamento',
                'verbose_name_plural': 'Aditamentos',
            },
        ),
    ]
