# Generated by Django 2.2.16 on 2022-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0040_aditamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditamento',
            name='valor_aditamento',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='aditamento',
            name='valor_mensal_atualizado',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='aditamento',
            name='valor_total_atualizado',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
