# Generated by Django 2.2.16 on 2022-08-22 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0041_auto_20220818_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_intercorrencia', models.CharField(choices=[('SUSPENSAO', 'Suspensão'), ('IMPEDIMENTO', 'Impedimento'), ('RESCISAO', 'Rescisão')], max_length=25)),
                ('data_inicial', models.DateField(null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(null=True, verbose_name='Data Final')),
                ('acrescentar_dias', models.BooleanField(default=False)),
                ('data_encerramento', models.DateField(null=True, verbose_name='Data de Encerramento')),
                ('motivo_suspensao', models.CharField(choices=[('UNILATERALMENTE_ADMINISTRACAO_PUBLICA', 'Unilateralmente pela Administração Pública'), ('UNILATERALMENTE_CONTRATADO', 'Unilateralmente pelo Contratado'), ('CONSENSUALMENTE', 'Consensualmente')], max_length=50)),
                ('opcao_suspensao', models.TextField(blank=True, verbose_name='Opção de Suspensão')),
                ('descricao_suspensao', models.TextField(blank=True, verbose_name='Descrição do Motivo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercorrencias', to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Intercorrência',
                'verbose_name_plural': 'Intercorrências',
            },
        ),
    ]
