# Generated by Django 2.2.16 on 2022-08-30 04:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0043_auto_20220824_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_intercorrencia', models.CharField(choices=[('SUSPENSAO', 'Suspensão'), ('IMPEDIMENTO', 'Impedimento'), ('RESCISAO', 'Rescisão')], max_length=25)),
                ('data_encerramento', models.DateField(null=True, verbose_name='Data de Encerramento')),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('vigencia', models.PositiveSmallIntegerField(default=0, verbose_name='vigência')),
                ('descricao_impedimento', models.TextField(verbose_name='Descrição do Motivo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
            ],
            options={
                'verbose_name': 'Impedimento',
                'verbose_name_plural': 'Impedimentos',
            },
        ),
        migrations.CreateModel(
            name='AnexoImpedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anexo', models.FileField(upload_to='uploads/')),
                ('impedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_impedimento', to='contratos.Impedimento')),
            ],
            options={
                'verbose_name': 'Anexo de Impedimento',
                'verbose_name_plural': 'Anexos de Impedimentos',
            },
        ),
    ]
