# Generated by Django 2.2.16 on 2022-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0045_auto_20220831_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='armazenabilidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='durabilidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_programa',
            field=models.CharField(blank=True, choices=[('ALIMENTO', 'Alimentação Escolar'), ('OUTROS', 'Leve Leite')], default='', max_length=25),
        ),
    ]
