# Generated by Django 2.2.4 on 2019-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20190918_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='divisoes',
            field=models.ManyToManyField(blank=True, to='core.Divisao'),
        ),
    ]
