# Generated by Django 2.2.4 on 2019-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20190919_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validado',
            field=models.BooleanField(default=False,
                                      help_text='Campo para verificar se o cadastro do usuário foi validado',
                                      verbose_name='Validado'),
        ),
    ]
