# Generated by Django 2.2.4 on 2019-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20190925_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_redefinicao',
            field=models.TextField(blank=True, default='',
                                   help_text='Campo utilizado para registrar hash na redefinição de senhas'),
        ),
    ]
