# Generated by Django 2.2.4 on 2019-10-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190930_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='divisoes',
        ),
    ]
