# Generated by Django 2.2.4 on 2019-09-18 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('divisoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisao',
            name='descricao',
        ),
    ]
