# Generated by Django 2.2.4 on 2019-10-28 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordenador_coad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'COAD',
            },
        ),
    ]
