# Generated by Django 2.2.4 on 2019-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_eol',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
