# Generated by Django 2.2.4 on 2019-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20190923_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='id',
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codigo_eol',
            field=models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False,
                                   unique=True),
        ),
    ]
