# Generated by Django 2.2.4 on 2019-10-28 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_coad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coad',
            options={'verbose_name': 'COAD', 'verbose_name_plural': 'COAD'},
        ),
        migrations.CreateModel(
            name='CoadAssessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessor_coad', to=settings.AUTH_USER_MODEL)),
                ('coad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessores', to='core.Coad')),
            ],
            options={
                'verbose_name': 'Assessor COAD',
                'verbose_name_plural': 'Assessores COAD',
            },
        ),
    ]
