# Generated by Django 2.2.4 on 2020-05-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_edital_grupoobrigacao_obrigacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoobrigacao',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_obrigacao', to='core.Edital'),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_obrigacao', to='core.GrupoObrigacao'),
        ),
    ]
