# Generated by Django 2.2.4 on 2019-10-28 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20191028_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisao',
            name='diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diretor_divisao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisao',
            name='suplente_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suplente_diretor_divisao', to=settings.AUTH_USER_MODEL),
        ),
    ]
