# Generated by Django 2.2.4 on 2020-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200528_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do Edital'),
        ),
    ]
