# Generated by Django 2.2.4 on 2020-05-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200519_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='dre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
