# Generated by Django 2.2.4 on 2019-10-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20191028_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleo',
            name='chefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chefe_nucleo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nucleo',
            name='suplente_chefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suplente_chefe_nucleo', to=settings.AUTH_USER_MODEL),
        ),
    ]
