# Generated by Django 2.2.4 on 2020-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unidade_dre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='dre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
