# Generated by Django 2.2.4 on 2020-05-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200529_1017'),
        ('core', '0006_unidade_dre'),
    ]

    operations = [
    ]
