# Generated by Django 2.2.4 on 2019-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='sigla',
            field=models.CharField(max_length=15, unique=True, verbose_name='Sigla'),
        ),
    ]
