# Generated by Django 2.2.4 on 2020-06-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20200530_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrigacao',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='GrupoObrigacao',
        ),
        migrations.DeleteModel(
            name='Obrigacao',
        ),
    ]
