# Generated by Django 2.2.4 on 2022-03-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_auto_20220304_1422'),
        ('core', '0007_merge_20200530_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoobrigacao',
            name='edital',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Edital',
        ),
        migrations.DeleteModel(
            name='GrupoObrigacao',
        ),
        migrations.DeleteModel(
            name='Obrigacao',
        ),
    ]
