# Generated by Django 2.2.4 on 2020-06-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200603_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoobrigacao',
            name='clausula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_obrigacao', to='core.ClausulaObrigacao'),
        ),
    ]
