# Generated by Django 2.2.4 on 2019-10-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191028_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='sigla',
            field=models.CharField(max_length=20, unique=True, verbose_name='Sigla'),
        ),
    ]
