# Generated by Django 2.2.4 on 2020-06-04 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200604_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClausulaObrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=350, verbose_name='Nome da Cláusula')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas_de_obrigacao', to='core.Edital')),
            ],
            options={
                'verbose_name': 'Cláusula de Obrigação',
                'verbose_name_plural': 'Cláusulas de Obrigações',
            },
        ),
        migrations.CreateModel(
            name='GrupoObrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(default='', max_length=15)),
                ('descricao', models.CharField(default='', max_length=350, verbose_name='Nome do Grupo')),
                ('clausula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_obrigacao', to='core.ClausulaObrigacao')),
            ],
            options={
                'verbose_name': 'Grupo de Obrigação',
                'verbose_name_plural': 'Grupos de Obrigações',
            },
        ),
        migrations.CreateModel(
            name='ItemObrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
                ('numero', models.CharField(default='', max_length=15)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_obrigacao', to='core.GrupoObrigacao')),
            ],
            options={
                'verbose_name': 'Item de Obrigação',
                'verbose_name_plural': 'Itens de Obrigações',
            },
        ),
        migrations.CreateModel(
            name='SubItemObrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Sub Item')),
                ('numero', models.CharField(max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_itens_de_obrigacao', to='core.ItemObrigacao')),
            ],
            options={
                'verbose_name': 'Sub Item de Obrigação',
                'verbose_name_plural': 'Sub Itens de Obrigações',
            },
        ),
    ]
