# Generated by Django 2.2.16 on 2022-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='subprefeitura',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
