# Generated by Django 2.2.4 on 2019-10-29 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191028_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadassessor',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessor_coad', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
