# Generated by Django 2.2.16 on 2022-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_unidade_subprefeitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='rg',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
