# Generated by Django 2.2.4 on 2019-10-29 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20191029_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coadassessor',
            name='assessor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assessor_coad',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
