# Generated by Django 2.2.4 on 2019-11-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20191029_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='dre',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='unidades_da_dre', to='core.Unidade'),
        ),
    ]
