# Generated by Django 2.2.4 on 2019-11-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_auto_20191128_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='dre',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='unidades_da_dre',
                                    to='core.Unidade'),
        ),
    ]
