# Generated by Django 2.2.16 on 2022-06-28 23:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoApiSofi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('endpoint', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='', max_length=10)),
                ('resultado', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Requisição da API Sofi',
                'verbose_name_plural': 'Requisições da API Sofi',
            },
        ),
    ]
